# Deployment preview app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "full_app_name" . }}-preview-deploy
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
        app: {{ include "full_app_name" . }}-preview
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "full_app_name" . }}-preview
        # humio-parser: eks
    spec:
      # serviceAccountName: {{ include "full_app_name" . }}-preview-service-account
      securityContext:
        fsGroup: {{ .Values.security_context.fs_group }}
      containers:
        - image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 256Mi
          name: {{ .Values.image.name }}-preview
          ports:
            - containerPort: {{ .Values.container_port }}
          env:
            # rename it to CONTENT_PUBLISH
            - name: STAGE
              value: preview
            # - name: CONTENT_PUBLISH
            #   value: preview
            - name: AWS_REGION
              value: {{ .Values.aws_region }}
            - name: "STATUS_DEPLOYID"
              value: "helm-{{ .Release.Name }}-{{ .Release.Revision }}"
            - name: "STATUS_DEPLOYDATE"
              value: "{{ dateInZone "2006-01-02 15:04:05 MST" (now) "UTC" }}"
            - name: "STATUS_ENVIRONMENTNAME"
              value: {{ .Values.environment_tag }}
            - name: "STATUS_INSTANCEID"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- range $key, $val := .Values.extra_envvars }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: {{ .Values.container_port }}
          #   initialDelaySeconds: 60
          #   periodSeconds: 15
