# NOTE: This should not be used with a VerticalPodAutoscaler.
# Use one or the other.
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "full_app_name" . }}-hpa
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "full_app_name" . }}-deploy
  targetCPUUtilizationPercentage: 75
